apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
data:
  index.html: |-
    <html>
      <head>
        <meta charset="UTF-8">
        <title>My App</title>
      </head>
      <body>
        <div id="root"></div>
        <script src="index.js"></script>
      </body>
    </html>
  package.json: |-
    {
      "name": "root",
      "version": "0.1.0",
      "private": true,
      "dependencies": {
        "@emotion/styled": "^11.10.0",
        "autoprefixer": "^10.4.8",
        "axios": "^0.27.2",
        "cors": "^2.8.5",
        "express": "^4.18.1",
        "mongoose": "^6.5.2",
        "postcss": "^8.4.16",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "react-hot-toast": "^2.3.0",
        "react-scripts": "5.0.1",
        "react-toastify": "^9.0.8",
        "tailwindcss": "^3.1.8",
        "twin.macro": "^2.8.2",
        "web-vitals": "^2.1.4"
      },
      "scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test",
        "eject": "react-scripts eject"
      },
      "eslintConfig": {
        "extends": [
          "react-app",
          "react-app/jest"
        ]
      },
      "browserslist": {
        "production": [
          ">0.2%",
          "not dead",
          "not op_mini all"
        ],
        "development": [
          "last 1 chrome version",
          "last 1 firefox version",
          "last 1 safari version"
        ]
      },
      "devDependencies": {
        "@testing-library/jest-dom": "^5.16.5",
        "@testing-library/react": "^13.3.0",
        "@testing-library/user-event": "^13.5.0"
      }
    }
