apiVersion: v1
kind: Secret
metadata:
  name: dockercreds
type: kubernetes.io/basic-auth
stringData:
  username: bm9ybXRoZWxpbnV4Z3V5   
  password: RnVlZ29MaWtlTm9ybXkx
---

apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: backend
spec:
  imagePullSecrets:
    - name: dockercreds
  containers:
    - name: api
      image: docker.io/normthelinuxguy/my-backend-image:latest
      env:
        - name: MONGO_USER
          value: admin
        - name: MONGO_PASSWORD
          value: admin
