
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
        - name: dockercreds
      initContainers:
        - name: npm-install
          image: node:latest
          command: ["npm", "install"]
          args: ["--prefix=/app"]
          volumeMounts:
            - name: app
              mountPath: /app
      containers:
        - name: frontend
          image: docker.io/normthelinuxguy/my-frontend-image:latest
          volumeMounts:
            - name: client-volume
              mountPath: /usr/share/nginx/html
        - name: nginx
          image: docker.io/normthelinuxguy/my-nginx-image:latest
          ports:
            - containerPort: 3051
          volumeMounts:
            - name: nginx-configmap
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
        - name: api
          image: docker.io/normthelinuxguy/my-backend-image:latest
          env:
            - name: MONGO_URI
              value: mongodb+srv://admin:acbV6EBjTA2D4gz1@stratfs-fullstack-js-te.dgc3mp1.mongodb.net/?retryWrites=true&w=majority
            - name: MONGO_USER
              value: admin
            - name: MONGO_PASSWORD
              value: admin
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: server-configmap
              mountPath: /app/config
      volumes:
        - name: client-volume
          configMap:
            name: client-configmap
            defaultMode: 420
        - name: nginx-configmap
          configMap:
            name: nginx-configmap
            defaultMode: 420
        - name: server-configmap
          configMap:
            name: server-configmap
            defaultMode: 420
        - name: app
          emptyDir: {}
