version: '3'
services:
  nginx: 
    restart: always
    image: 'nginx:latest'
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:3051'
    depends_on:
      - api
      - client
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    environment:
      - MONGO_USER=admin
      - MONGO_PASSWORD=admin
    volumes:
      - '/app/node_modules'
      - './server:/app'
  client: 
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - '/app/node_modules'
      - './client:/app'
    command: npm run start
    tty: true

