apiVersion: v1
kind: Secret
metadata:
  name: dockercreds
type: kubernetes.io/basic-auth
stringData:
  username: bm9ybXRoZWxpbnV4Z3V5   
  password: RnVlZ29MaWtlTm9ybXkx

---

apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend
spec:
  imagePullSecrets:
    - name: dockercreds
  containers:
    - name: client
      image: docker.io/normthelinuxguy/my-frontend-image:latest
      volumeMounts:
        - name: client-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: client-volume
      configMap:
        name: client-config
