apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  imagePullSecrets:
    - name: dockercreds
  containers:
    - name: nginx
      image: docker.io/normthelinuxguy/my-nginx-image:latest
      ports:
        - containerPort: 3051
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-config
