apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: myapp
    tier: frontend
  ports:
  - name: http
    port: 80
    targetPort: 3051
  - name: https
    port: 443
    targetPort: 3051
  type: ClusterIP
