version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:20.04
    steps:
      - checkout
      - run:
          name: Build Docker images
          command: |
            docker build -t server ./server
            docker tag server:latest docker.io/normthelinuxguy/my-backend-image:latest
            docker build -t my-nginx-image ./nginx
            docker tag my-nginx-image:latest docker.io/normthelinuxguy/my-nginx-image:latest
            docker build -t client ./client 
            docker tag client:latest docker.io/normthelinuxguy/my-frontend-image:latest

  deploy:
    docker:
      - image: bitnami/kubectl:latest
    steps:
      - checkout
      - run:
          name: Deploy backend and frontend images to Kubernetes
          command: |
            kubectl set image deployment/server-deployment server=docker.io/normthelinuxguy/my-backend-image:latest
            kubectl set image deployment/nginx-deployment nginx=docker.io/normthelinuxguy/my-nginx-image:latest
            kubectl set image deployment/client-deployment client=docker.io/normthelinuxguy/my-frontend-image:latest

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - deploy
