version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:20.04
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get update
            sudo apt-get -y install curl
            curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o docker-compose
            sudo mv docker-compose /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
      - run:
          name: Build and push Docker images
          command: |
            docker build -t server ./server
            docker tag server:latest docker.io/normthelinuxguy/my-backend-image:latest
            docker push docker.io/normthelinuxguy/my-backend-image:latest
            docker build -t my-nginx-image ./nginx
            docker tag my-nginx-image:latest docker.io/normthelinuxguy/my-nginx-image:latest
            docker push docker.io/normthelinuxguy/my-nginx-image:latest
            docker build -t client . 
            docker tag client:latest docker.io/normthelinuxguy/my-frontend-image:latest
            docker push docker.io/normthelinuxguy/my-frontend-image:latest

  test:
    docker:
      - image: docker/compose:1.29.2
    steps:
      - checkout
      - run:
          name: Run backend tests
          command: |
            docker-compose
workflows:
  version: 2
  build-and-test:
    jobs:
      - test
      - build:
          requires:
            - test
