version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10.9
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            apt-get update
            apt-get install -y curl
            curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
          name: Build and push Docker images
          command: |
            docker-compose build
            docker tag my-backend-image:latest docker.io/normthelinuxguy/my-backend-image:latest
            docker push docker.io/normthelinuxguy/my-backend-image:latest
            docker tag my-nginx-image:latest docker.io/normthelinuxguy/my-nginx-image:latest
            docker push docker.io/normthelinuxguy/my-nginx-image:latest
            docker tag my-frontend-image:latest docker.io/normthelinuxguy/my-frontend-image:latest
            docker push docker.io/normthelinuxguy/my-frontend-image:latest

  test:
    docker:
      - image: docker/compose:1.29.2
    steps:
      - checkout
      - run:
          name: Run backend tests
          command: |
            docker-compose
workflows:
  version: 2
  build-and-test:
    jobs:
      - test
      - build:
          requires:
            - test
