version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build backend image
          command: |
            docker-compose build server
            docker tag my-backend-image:latest docker.io/normthelinuxguy/my-backend-image:latest
            docker push docker.io/normthelinuxguy/my-backend-image:latest
      - run:
          name: Build nginx image
          command: |
            docker-compose build nginx
            docker tag my-nginx-image:latest docker.io/normthelinuxguy/my-nginx-image:latest
            docker push docker.io/normthelinuxguy/my-nginx-image:latest
      - run:
          name: Build frontend image
          command: |
            docker-compose build client
            docker tag my-frontend-image:latest docker.io/normthelinuxguy/my-frontend-image:latest
            docker push docker.io/normthelinuxguy/my-frontend-image:latest

  test:
    docker:
      - image: docker/compose:1.29.2
    steps:
      - checkout
      - run:
          name: Run backend tests
          command: |
            docker-compose
workflows:
  version: 2
  build-and-test:
    jobs:
      - test
      - build:
          requires:
            - test
