apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  server.js: |-
    require("dotenv").config();
    const app = require("./app");

    // App configuration
    const PORT = process.env.PORT || 5000;

    // Start server
    app.listen(PORT, console.log(`Server started on port ${PORT}`));
  
  package.json: |-
    {
      "dependencies": {
        "cors": "2.8.5",
        "dotenv": "^16.0.3",
        "express": "4.18.2",
        "mongoose": "7.0.3",
        "node-dev": "^7.0.0"
      },
      "scripts": {
        "dev": "node-dev --respawn --notify --watch ./src --ignore node_modules server.js",
        "start": "node server.js"
      }
    }
